"""add report email status tracking to orders

Revision ID: 28994a85b1b9
Revises: 4d0f16d582e3
Create Date: 2026-09-04 02:15:58.558291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28994a85b1b9'
down_revision = '4d0f16d582e3'
branch_labels = None
depends_on = None


def upgrade():
    # Task 17B review fix: autogenerate emitted email_status as NOT NULL
    # with no server_default -- safe against an EMPTY table (local dev),
    # but would fail outright against production's existing orders rows
    # (Postgres rejects adding a NOT NULL column with no default to a
    # non-empty table). server_default matches this repo's own established
    # convention for exactly this situation (see e.g. ai_reports.status's
    # own server_default='PENDING' in a1c4e9f7d2b3) and the model's own
    # Python-side default="NOT_ATTEMPTED" -- every existing Order row
    # backfills to the truthful state (no email has been attempted under
    # this new tracking), never a fabricated SENT/FAILED guess.
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_status', sa.String(length=20), nullable=False, server_default='NOT_ATTEMPTED'))
        batch_op.add_column(sa.Column('email_last_attempt_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('email_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('email_error', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('email_error')
        batch_op.drop_column('email_sent_at')
        batch_op.drop_column('email_last_attempt_at')
        batch_op.drop_column('email_status')

    # ### end Alembic commands ###
