"""add activity events ledger

Revision ID: 4d0f16d582e3
Revises: c7d2f5a9e1b3
Create Date: 2026-09-01 01:34:36.161603

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d0f16d582e3'
down_revision = 'c7d2f5a9e1b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_name', sa.String(length=64), nullable=False),
    sa.Column('event_version', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('firebase_uid', sa.String(length=255), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('anonymous_id', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('entity_type', sa.String(length=32), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('campaign_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notification_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dedupe_key', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_events_anonymous_id'), ['anonymous_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_events_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index('ix_activity_events_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_activity_events_event_name_occurred_at', ['event_name', 'occurred_at'], unique=False)
        batch_op.create_index('ix_activity_events_firebase_uid_occurred_at', ['firebase_uid', 'occurred_at'], unique=False)
        batch_op.create_index('ix_activity_events_occurred_at', ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_events_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_events_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ux_activity_events_dedupe_key', ['dedupe_key'], unique=True, postgresql_where=sa.text('dedupe_key IS NOT NULL'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.drop_index('ux_activity_events_dedupe_key', postgresql_where=sa.text('dedupe_key IS NOT NULL'))
        batch_op.drop_index(batch_op.f('ix_activity_events_session_id'))
        batch_op.drop_index(batch_op.f('ix_activity_events_profile_id'))
        batch_op.drop_index('ix_activity_events_occurred_at')
        batch_op.drop_index('ix_activity_events_firebase_uid_occurred_at')
        batch_op.drop_index('ix_activity_events_event_name_occurred_at')
        batch_op.drop_index('ix_activity_events_entity')
        batch_op.drop_index(batch_op.f('ix_activity_events_correlation_id'))
        batch_op.drop_index(batch_op.f('ix_activity_events_anonymous_id'))

    op.drop_table('activity_events')
    # ### end Alembic commands ###
