"""added language, report_stage, pdf_url

Revision ID: 5d187f5f47bb
Revises: 
Create Date: 2025-09-07 00:24:57.770100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d187f5f47bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('report_stage', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('pdf_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('pdf_url')
        batch_op.drop_column('report_stage')
        batch_op.drop_column('language')

    # ### end Alembic commands ###
