"""add static astrology fields to app_users

Revision ID: 6816ff4a7cf5
Revises: 0e2036a0b4b7
Create Date: 2026-09-06 20:11:54.274722

U3B.1 -- the frozen U3B storage architecture decision (Pada as a
dedicated column, Yog/Dosh as sparse JSONB, one shared calculated_at +
version pair). Purely additive: 5 new nullable columns on app_users,
no server_default, no data rewrite, no backfill, no index. Every
existing row reads NULL for all five after this migration -- NULL is
the correct, intentional "not calculated yet" state (see
modules/services/static_astrology_extractor.py), never something to
backfill as part of this migration. A future, separately-controlled
U3B.2 backfill is the only thing that will ever populate these columns
for pre-existing rows.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6816ff4a7cf5'
down_revision = '0e2036a0b4b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nakshatra_pada', sa.SmallInteger(), nullable=True))
        batch_op.add_column(sa.Column('static_yog', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('static_dosh', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('static_astrology_calculated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('static_astrology_version', sa.SmallInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_users', schema=None) as batch_op:
        batch_op.drop_column('static_astrology_version')
        batch_op.drop_column('static_astrology_calculated_at')
        batch_op.drop_column('static_dosh')
        batch_op.drop_column('static_yog')
        batch_op.drop_column('nakshatra_pada')

    # ### end Alembic commands ###
