"""Add new fields safely

Revision ID: a4fe16131d4c
Revises: f5ddd4e76ced
Create Date: 2025-09-22 00:17:09.743417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4fe16131d4c'
down_revision = 'f5ddd4e76ced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
