# config/pricing.py

PRODUCT_PRICES = {
    "marriage_report": 51,
    "career_report": 51,
    "love_relationship_report": 51,
    "foreign_travel_report": 51,
    "government_job_report": 51,
    "sadhesati_report": 51,
    "financial_report": 51,
    "startup_suggestion_report": 51,
    "love_marriage_report": 51,
    "business_report": 51,
    "legal_disputes_report": 51,
    "gemstone_consultation": 51,
    "children_parenting_report": 51,
    "delay_in_marriage_report": 51,
    "financial_stability_report": 51,
    "jupiter_transit_report": 51,
    "lifestyle_analysis_report": 51,
    "love_disappointment_report": 51,
    "problem_in_marriage_report": 51,
    "mood_mental_health_report": 51,
    "property_report": 51,
    "saturn_transit_report": 51,
    "second_marriage_report": 51,
    "divorce_possibility_report": 51,
    "relationship_future_report": 299,
    # Add more here...
}
