# modules/payments/report_ai_client.py

"""
report_ai_client.py -- Paid Report Platform, Q3 Batch 0.

The ONE authoritative AI client for paid-report generation -- both
standard_v1 (tasks.py) and love_premium_v1 (modules/love/
love_premium_task.py) are wired to call generate_report_completion()
below instead of each constructing/calling its own OpenAI client.
Scoped exclusively to paid-report generation: does NOT import from,
share state with, or modify any other OpenAI integration in this
codebase (modules/services/chat_engine.py, modules/services/
chat_requirement_engine.py, modules/smartchat/smartchat_engine.py,
services/ai_prediction_lab/, report_writer.py,
routes/routes_free_consult.py all keep their own separate client
instances -- Quest/chat/AI-lab systems are completely untouched by
this module).

MODEL: PAID_REPORT_AI_MODEL (app_config.py -- the single authoritative
source, alongside that module's existing USE_CELERY toggle). Currently
"gpt-5.6-luna".

TEMPERATURE: never sent. gpt-5.6-luna is confirmed (verified against
the live OpenAI API, not assumed -- see services/ai_prediction_lab/
openai_client.py's own comment, the original source of this finding in
this repository) to reject a custom `temperature` value with a 400
"Unsupported value... Only the default (1) value is supported" error.
Neither tasks.py nor modules/love/love_premium_task.py has ever sent a
custom temperature to begin with, so omitting it here is a
zero-behavior-change decision, not a new restriction.

NO AUTOMATIC MODEL FALLBACK (Q3 Batch 0, locked correction #2): a Luna
call failure of any kind (network, auth, rate-limit, malformed
response) is raised straight through to the caller. This module never
catches an exception here and retries against gpt-4o-mini or any other
model. Report generation is expected to fail via the EXISTING
report_stage="Failed" path (F2 ReconciliationService recovery) exactly
as an OpenAI failure already does today -- this is a deliberate
report-quality/observability decision (every paid report must be
generated by the same, known model, and a Luna outage must be visibly
observable rather than silently masked by a cheaper/different model),
not an oversight.

NO PII, NO PROMPT/RESPONSE CONTENT IS EVER LOGGED BY THIS MODULE. Only
the model name, token counts, and call duration are captured (see
ReportAICompletion below) -- never the prompt text, never the response
text, never name/email/DOB/TOB/POB. Callers are responsible for the
same discipline in whatever they do with `.content` afterward (this
module has no opinion on that -- it simply returns the string).
"""

from __future__ import annotations

import os
import time
from dataclasses import dataclass
from typing import Optional

from dotenv import load_dotenv
from openai import OpenAI

from app_config import PAID_REPORT_AI_MODEL

load_dotenv()

# Lazy singleton -- constructed on first REAL use (the first call to
# generate_report_completion()), not merely by importing this module.
# Mirrors the exact, already-proven pattern services/ai_prediction_lab/
# openai_client.py uses (see that file's own docstring for the
# rationale) -- deliberately NOT imported from there directly, since
# that file's own docstring explicitly declares itself isolated from
# every production OpenAI integration, paid reports included; this is
# a fresh, separate instance scoped to this module alone.
_client: Optional[OpenAI] = None


def _get_client() -> OpenAI:
    global _client
    if _client is None:
        _client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
    return _client


@dataclass(frozen=True)
class ReportAICompletion:
    """Everything a paid-report caller needs from one Luna call.

    `content` is the raw response text exactly as Luna returned it --
    still needs downstream handling (either the existing
    convert_headings() narrative pipeline directly, for a product that
    is not yet q3_enabled, or report_structured_output.py's
    parse_structured_response() first, for one that is). Never logged
    by this module.

    Token fields are None only if the API response genuinely omitted
    `usage` (not expected in normal operation, but never fabricated a
    number if it did)."""
    content: str
    model: str
    input_tokens: Optional[int]
    output_tokens: Optional[int]
    total_tokens: Optional[int]
    duration_seconds: float


def generate_report_completion(prompt: str) -> ReportAICompletion:
    """The ONE call site both paid-report generators use.

    Raises whatever the underlying OpenAI SDK call raises (network
    error, auth error, rate limit, etc.) -- deliberately NOT caught or
    retried against a different model here (see module docstring's "no
    automatic fallback" rule). The caller's own existing exception
    handling (report_stage="Failed", unchanged by this module) is the
    correct and only place that failure is handled."""
    started = time.monotonic()
    response = _get_client().chat.completions.create(
        model=PAID_REPORT_AI_MODEL,
        messages=[{"role": "user", "content": prompt}],
        # No `temperature` kwarg -- see module docstring.
    )
    duration_seconds = time.monotonic() - started

    usage = getattr(response, "usage", None)
    return ReportAICompletion(
        content=response.choices[0].message.content.strip(),
        model=PAID_REPORT_AI_MODEL,
        input_tokens=getattr(usage, "prompt_tokens", None) if usage is not None else None,
        output_tokens=getattr(usage, "completion_tokens", None) if usage is not None else None,
        total_tokens=getattr(usage, "total_tokens", None) if usage is not None else None,
        duration_seconds=duration_seconds,
    )
